# Generated by Django 4.1.5 on 2023-09-21 12:52

import pathlib

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("img", "Image"), ("doc", "Document")],
                        max_length=10,
                    ),
                ),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=8192)),
                (
                    "faiss_store",
                    models.FilePathField(
                        path=pathlib.PurePosixPath(
                            "/home/ershan/projects/django_projects/chatbot_project/chatbot/media/faiss"  # noqa
                        )
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
