# Generated by Django 4.1.5 on 2023-09-21 13:14

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_document_created_at_document_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="faiss_store",
            field=models.FilePathField(
                null=True,
                path=pathlib.PurePosixPath(
                    "/home/ershan/projects/django_projects/chatbot_project/chatbot/media/faiss"  # noqa
                ),
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("img", "Image"), ("doc", "Document")],
                max_length=10,
                null=True,
            ),
        ),
    ]
