# Generated by Django 4.1.5 on 2023-09-21 13:15

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0003_alter_document_faiss_store_alter_document_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="faiss_store",
            field=models.FilePathField(
                blank=True,
                default="",
                path=pathlib.PurePosixPath(
                    "/home/ershan/projects/django_projects/chatbot_project/chatbot/media/faiss"  # noqa
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[("pdf", "PDF"), ("img", "Image"), ("doc", "Document")],
                max_length=10,
            ),
        ),
    ]
