# Generated by Django 4.1.5 on 2023-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_alter_document_faiss_store_alter_document_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
