# Generated by Django 4.1.5 on 2023-09-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_document_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF"),
                    ("img", "Image"),
                    ("doc", "Document"),
                    ("html", "HTML"),
                ],
                max_length=10,
            ),
        ),
    ]
