# Generated by Django 4.1.5 on 2023-09-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0007_alter_document_filename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="faiss_store",
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
