# Generated by Django 4.1.5 on 2023-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_message_type_to_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=4),
        ),
    ]
