# Generated by Django 4.1.5 on 2023-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_message_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=4000)),
                ("content", models.TextField()),
            ],
        ),
    ]
