# Generated by Django 4.1.5 on 2023-08-30 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_session_message_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="session",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.session",
            ),
            preserve_default=False,
        ),
    ]
