# Generated by Django 4.1.5 on 2023-08-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_message_session"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Session",
            new_name="Conversation",
        ),
    ]
