# Generated by Django 4.1.5 on 2023-08-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_conversation_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="session",
            new_name="conversation",
        ),
    ]
