# Generated by Django 4.1.5 on 2023-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_rename_session_message_conversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
