# Generated by Django 4.1.5 on 2023-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_alter_document_faiss_store"),
        ("chat", "0012_conversation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="context",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="message",
            name="documents",
            field=models.ManyToManyField(
                blank=True, related_name="chats", to="document.document"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="system_prompt",
            field=models.TextField(blank=True),
        ),
    ]
